title = "About [this]"


[[text]]
v = """
    Since the cultural embrace of Facebook, and social media as a whole more than a decade ago the voice and mind of
    the average has been marginalized into status updates powered by "likes" and other superficial nonsense. The Blogisphere
    that powered ambitious people's thoughts before the dawn of social media still exists and in some realms still thrives,
    but for the masses it's too much work. This little website I am creating here is no mere blog, nor is it a vain attempt
    to replace my social media fix (if one even exists); rather this is my contribution to a very complex human world where
    I admit I often feel very lost.
"""

[[text]]
v = """
    Philosophically I have stepped away from the social monster god that has power over most of us, but this doesn't mean that I have nothing to say.
    This project, this website, this something that might end up looking like and becoming a blog is my public tracking tool.
    If I have something to say, I will write it here first, and over time I will continue to build this up into something that looks
    more less like a txt file, and more like a modern web journal.
"""

[[text]]
v = """
    If you are interested in what tool I am using to write / publish this I will post my updates to the [#Maxwell] page. Write now Maxwell
    is very backend, and in a very "I can care less about how this looks, my job is to organize all this data" stage of development. So
    I am excited to see how this goes.
"""