# This is a toml index content

root = "about"

[[post]]
key = "philo/epictetus"
imp = "philo/epictetus.toml"

[[post]]
key = "52books2021"
imp = "52books2021/blog.toml"

[[post]]
key = "about"
imp = "about.toml"