# This is a sample toml file representing a Maxwell post

title = "Something Profound on Epictetus"

[[text]]
v = """
    This is a text segment with some fairly profound arguments in support of Epictetus.
"""

[[text]]
v = "This is a bit more of the above rant on Epictetus."

[[ref]]
name = """Epictetus' "The Manual" [Enchiridion]"""
url = "http://classics.mit.edu/Epictetus/epicench.html"

[[audio]]
url = "https://pyramid.media/some-audio-file.mp3"


[[text]]
v = "and finally something else... maybe an ending."