title = "One Book Per Week of 2021"

[[text]]
v = """
    In 2020 I made a goal to hike 500 miles. I ended up hiking 283 miles and taking 213 miles of walks. I really don't feel
    like mincing words over whether I succeeded or not, because I feel good about it, and only I know the challenges that hindered
    my progress.
"""

[[text]]
v = """
    But for 2021, I don't want to make another hiking goal, I plan on continuing on that trend, but without as much metrics. I do
    want to push myself though, and I want to lift my mind to a more lofty sphere, so after hardly any thinking to be honest, I have
    decided that for 2021 my goal is to read one book per week. I will mix it up between the genres I can stand, and maybe throw
    in a few surprises. This blog will act as a tracking tool for my progress, and insights on each of the books I take on this year.
"""
